apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: hl7-fhir-trustore
spec:
  secretName: hl7-fhir-trustore
  type: truststore
  version: {{ .Values.ibm_ace_server_instance.ace_version }}
