apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: hl7-server-conf
spec:
  contents: >-
    UmVzb3VyY2VNYW5hZ2VyczoKICBKVk06CiAgICBqdm1EZWJ1Z1BvcnQ6IDk5OTggICAgICAgICAgICAgICAgICMgU2V0IG5vbi16ZXJvIHRvIGFjdGl2YXRlIEpWTSBkZWJ1ZyBwb3J0IGZvciBUb29sa2l0IGRlYnVnZ2luZwogICAgI2p2bVN5c3RlbVByb3BlcnR5OiAnJwogICAga2V5c3RvcmVUeXBlOiAnSktTJyAgICAgICAgICAgICAgICAjIEpWTSBrZXkgc3RvcmUgdHlwZQogICAga2V5c3RvcmVGaWxlOiAnL2hvbWUvYWNldXNlci9rZXlzdG9yZXMvaGw3LWZoaXIua2V5c3RvcmUuamtzJyAgICAgICAgICAgICAgICAjIEpWTSBsb2NhdGlvbiBvZiB0aGUga2V5IHN0b3JlCiAgICBrZXlzdG9yZVBhc3M6ICdhY2UtY2xpZW50OjprZXlzdG9yZVBhc3MnICAgICAgICAgICAgICAgICMgSlZNIHJlc291cmNlIGFsaWFzIGNvbnRhaW5pbmcgdGhlIGtleSBzdG9yZSBwYXNzd29yZAogICAgdHJ1c3RzdG9yZVR5cGU6ICdKS1MnICAgICAgICAgICAgICAgIyBKVk0gdHJ1c3Qgc3RvcmUgdHlwZQogICAgdHJ1c3RzdG9yZUZpbGU6ICcvaG9tZS9hY2V1c2VyL3RydXN0c3RvcmVzL2hsNy1maGlyLnRydXN0c3RvcmUuamtzJyAgICAgICAgICAgICAgIyBKVk0gbG9jYXRpb24gb2YgdGhlIHRydXN0IHN0b3JlCiAgICB0cnVzdHN0b3JlUGFzczogJ2FjZS1jbGllbnQ6OnRydXN0c3RvcmVQYXNzJyAgICAgICAgICAgICAgIyBKVk0gcmVzb3VyY2UgYWxpYXMgY29udGFpbmluZyB0aGUgdHJ1c3Qgc3RvcmUgcGFzc3dvcmQ=
  type: serverconf
  version: {{ .Values.ibm_ace_server_instance.ace_version }}
