apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-cp-ace-demoapp-v1-demo-app-v1
spec:
  destination:
    namespace: gitops-cp-ace-demoapp-v1
    server: https://kubernetes.default.svc
  project: 3-applications
  source:
    path: payload/3-applications/namespace/gitops-cp-ace-demoapp-v1/demo-app-v1
    repoURL: https://github.com/cloud-native-toolkit-gj-ka/gitops-cp-app-demoapp-v1
    targetRevision: main
    helm:
      releaseName: demo-app-v1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
