apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: gitops-cp-ace-demoapp-v1
spec:
  encryptedData:
    .dockerconfigjson: AgCooikR7tMQgqjPjUye2cINBp/54RlQ3OisfGN+N/ID+38ruZsOZ+qRV8U4RASt+GIkuaodWXNDaRyqRTpgdx7HFgAtV4es2UNh4rOaDY8CxOFd99+YeVrlBMYdgZC39XTPcoJnn1CQpTRKPEqGp2Mf3fKOLxgr+q8AB+kTHp0a74/mke/jMgmKRjqKdl8Y0ujVGY5OdppJBH7xHuNjwGG4ylNH53rFhxz9OOUzF7CzelFLPg3Ob4jhFQEm1AdjK/kuvei9oNfu3M3RDbwfqqa2ZVgLKgtPj1F8ne1I3BoQkB0QqwifGyniotry1LMhyebNHjL49n2hp5uzklrPh+kxJd0kuMpbqdSEAwF10l9kLfoSPi92sZRSzvyRuGnAaql1nRCOLv7fJjEdzRLbNrSnSmm1H6vmpbrChWkpt3zJccJRqNzb9eXo9OK9JbiQpYyY6CSws35tkXAZ1gzZqJnoIgjNYzrsOqU5pAY4jQ6zBZPCdXVv6v9MmwMpZV5ZWvIIyd7k0F7wG5unSNsuRWlQj0xZJ/Ee/woyzxmZiN3wh+Jt11XegHQQLKMdSatLCNrpvh7PxGDuRxY2wucm9htxaDLFAohKalyOIRi9R0G01jooPE+5x+Nt4SNvWhCF/CEpc5ufZMKH8XzB5juvwBfC+URJNrygvcI+CQpfiNwcFRex1sH88GbLJPVKOUwTr6vD7Tx/dFdL/rwJoK1Iq+LZFuGzc5tbcW7N6eCFp6Vq9xedN7SutzbGMccYWwuTJRUo7vr0F1dcG6aXDbmIH1W0AzMoKLNcIw0nRyFjussk5ExK7UEliLalIMlKkZFNwm6me+MDSESpW3bG7a+RioBD/ZFloUEb25JstcZXrXKTdFbyY27QQnv7IvQMmbJ+QMs+Ww1Hl6G1IZXr0tiI83i4meoN2nzyu46hGtADEsFH3sSdVBoCJEiokcHZ/niIYZFmMS9oyirfsu2MEypcrd207O0Y9v35plMVYnFa75tXPMg+LuAvdaSJlZUX/T8En2JtHRLDVu9cagINL+c76E55aTp9L8X54AZCDTBlKwWDdHhbxN63nNHdHFNGlcJJO3COoB7PjAWTSEgyYBRGCRnQmQPF8e0qauNGgdmq9nzUFtpK6J8+rHPAreGaUQD7cI5mZcWUVMNsdEySlLIK9tdmHTQ35nJBlPmQWUl+LqILshmW/TjPN2rz/CMqNJ0uWFnAJ/GIoBwDGRmkD+JHJX9+5PXj5ABbGraJ90KNGeBK23gVTZfLGH+FuuyMdn0ems4D93hBvXxbLTnIgjy26GCdx8pmsZFjqnhn9J/qg1kzQbMTVjqd5IvxNkcXYM6i5emk
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: gitops-cp-ace-demoapp-v1
    type: kubernetes.io/dockerconfigjson

